#!/bin/sh
# Disable screen blanking/power saving for kiosk
xset s off
xset -dpms
xset s noblank

# Start sxhkd (hotkey daemon)
sxhkd -c ~/.config/sxhkd/sxhkdrc &

# Launch Proxmox UI fullscreen with extension
exec chromium \
  --kiosk \
  --no-first-run \
  --disable-translate \
  --disable-features=TranslateUI \
  --disk-cache-dir=/tmp/chromium-cache \
  --load-extension=/home/kiosk/proxmox-switcher-os/extension \
  https://127.0.0.1:8006/
